from collections import deque
from typing import Deque

from bosch_ASDIIE_Git_egylet.solid_version.core.canvas import Canvas
from bosch_ASDIIE_Git_egylet.solid_version.core.game_element import GameElement
from bosch_ASDIIE_Git_egylet.solid_version.core.key_event import KeyEvent
from bosch_ASDIIE_Git_egylet.solid_version.core.map import Coordinates, MapSize
from bosch_ASDIIE_Git_egylet.solid_version.core.visualizable import Visualizable
from bosch_ASDIIE_Git_egylet.solid_version.core.moving_transformation import MovingTransformation